# Generated by Django 5.1.5 on 2025-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
